# Generated by Django 5.2.1 on 2026-04-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_tenant_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['due_date']},
        ),
        migrations.AddField(
            model_name='payment',
            name='last_reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', '-due_date'], name='properties__tenant__30a2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid', 'due_date'], name='properties__paid_0d64f6_idx'),
        ),
    ]
