# Generated by Django 6.0.4 on 2026-04-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_payment_options_payment_last_reminder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
