# Generated by Django 5.2.1 on 2026-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('landlord', 'Landlord'), ('tenant', 'Tenant')], default='tenant', max_length=10),
        ),
    ]
